Controllers/clientesController.cs
using kairh_admin.Models;
using kairh_admin.Models.firebase;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kairh_admin.Controllers
{
    public class clientesController : Controller
    {

        private readonly MyDbContext _context;
        public firebaseCliente _firebase { get; set; }


        public clientesController(MyDbContext context)
        {
            _context = context;
            _firebase = new firebaseCliente();
        }
        public async Task<IActionResult> Index()
        {
            // Consultar la nube
            var data = _firebase.list();
            foreach (var item in data)
            {
                MyFbContext.modelCliente model = JsonConvert.DeserializeObject<MyFbContext.modelCliente>(((JProperty)item).Value.ToString());
                string llave = item.Name.ToString();

                // Modelo real
                var m = new cliente
                {
                    idcliente = llave,
                    apellidos = model.apellidos,
                    callePred = model.callePred,
                    ciudadPred = model.ciudadPred,
                    clave = model.clave,
                    coloniaPred = model.coloniaPred,
                    correo = model.correo,
                    cpPred = model.cpPred,
                    estadoPred = model.estadoPred,
                    latPred = model.latPred,
                    lonPred = model.lonPred,
                    municipioPred = model.municipioPred,
                    noExtPred = model.noExtPred,
                    noIntPred = model.noIntPred,
                    nombres = model.nombres,
                    telefono = model.telefono,
                };

                if (clienteExists(m.idcliente).Equals(true))
                {
                    var cte = await _context.Clientes.FirstOrDefaultAsync(o => o.idcliente == m.idcliente);
                    cte.idcliente = llave;
                    cte.apellidos = model.apellidos;
                    cte.callePred = model.callePred;
                    cte.ciudadPred = model.ciudadPred;
                    cte.clave = model.clave;
                    cte.coloniaPred = model.coloniaPred;
                    cte.correo = model.correo;
                    cte.cpPred = model.cpPred;
                    cte.estadoPred = model.estadoPred;
                    cte.latPred = model.latPred;
                    cte.lonPred = model.lonPred;
                    cte.municipioPred = model.municipioPred;
                    cte.noExtPred = model.noExtPred;
                    cte.noIntPred = model.noIntPred;
                    cte.nombres = model.nombres;
                    cte.telefono = model.telefono;

                    _context.Update(cte);
                    await _context.SaveChangesAsync();
                }
                else
                {

                    _context.Add(m);
                    await _context.SaveChangesAsync();
                }

            }

            return View(await _context.Clientes.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string searchString, string campo)
        {
            var clientes = from m in _context.Clientes
                           select m;


            switch (campo)
            {
                case "Nombre":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        clientes = clientes.Where(s => (s.nombres+" "+s.apellidos)!.Contains(searchString));
                        //clientes = clientes.Where(s => s.apellidos!.Contains(searchString));
                    }
                    break;
                case "Telefono":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        clientes = clientes.Where(s => s.telefono!.Contains(searchString));
                    }
                    break;
                //case "Estatus":
                //    if (!String.IsNullOrEmpty(searchString))
                //    {
                //        clientes = clientes.Where(s => s.Estatus.Equals(searchString));
                //    }
                //    break;
            }

            return View(await clientes.ToListAsync());
        }
        private bool clienteExists(string idcliente)
        {
            return _context.Clientes.Any(e => e.idcliente == idcliente);
        }
        private bool clienteExists(int id)
        {
            return _context.Clientes.Any(e => e.id == id);
        }
    }
}

Controllers/pedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kairh_admin.Models;

namespace kairh_admin.Controllers
{
    public class pedidosController : Controller
    {
        private readonly MyDbContext _context;

        public pedidosController(MyDbContext context)
        {
            _context = context;
        }

        // GET: pedidos
        public async Task<IActionResult> Index()
        {
            // AQUI
            return View(await _context.Pedidos.ToListAsync());
        }

        //// GET: pedidos/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var pedido = await _context.Pedidos
        //        .FirstOrDefaultAsync(m => m.id == id);
        //    if (pedido == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(pedido);
        //}

        //// GET: pedidos/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: pedidos/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("id,idpedido,fecha,fechaentregado,fecharecibido,flagRecolecta,flagprop,folio,hora,horaentregado,horarecibido,idcliente,idnegocio,idrepartidor,latentrega,lonentrega,metodopago,montoEnvio,nombreNegocio,nombrerepartidor,propina,subtotal,tarifa,telrepartidor,total,urlnegocio")] pedido pedido)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(pedido);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(pedido);
        //}

        //// GET: pedidos/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var pedido = await _context.Pedidos.FindAsync(id);
        //    if (pedido == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(pedido);
        //}

        //// POST: pedidos/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("id,idpedido,fecha,fechaentregado,fecharecibido,flagRecolecta,flagprop,folio,hora,horaentregado,horarecibido,idcliente,idnegocio,idrepartidor,latentrega,lonentrega,metodopago,montoEnvio,nombreNegocio,nombrerepartidor,propina,subtotal,tarifa,telrepartidor,total,urlnegocio")] pedido pedido)
        //{
        //    if (id != pedido.id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(pedido);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!pedidoExists(pedido.id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(pedido);
        //}

        //// GET: pedidos/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var pedido = await _context.Pedidos
        //        .FirstOrDefaultAsync(m => m.id == id);
        //    if (pedido == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(pedido);
        //}

        //// POST: pedidos/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var pedido = await _context.Pedidos.FindAsync(id);
        //    _context.Pedidos.Remove(pedido);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool pedidoExists(int id)
        //{
        //    return _context.Pedidos.Any(e => e.id == id);
        //}
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kairh Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/kair1.jpeg" class="rounded d-block" width="35" alt="..."></a>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kairh</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="repartidores" asp-action="Index">Repartidores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="negocios" asp-action="Index">Negocios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="clientes" asp-action="Index">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="pedidos" asp-action="Index">Pedidos</a>
                            </li>
                            @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        </ul>
                    </div>
</div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Kairh Admin - Desarrollado por <a href="https://www.manticoretech.org/">Manticore Tecnologies</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/modalform.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<div id="modalGenerica" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="contentModal">
                <div id="resultado"></div>
            </div>
        </div>
    </div>
</div>