Controllers/negociosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kairh_admin.Models;
using FireSharp;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using kairh_admin.Models.firebase;

namespace kairh_admin.Controllers
{
    public class negociosController : Controller
    {

        private readonly MyDbContext _context;
        public firebaseNegocio _firebase { get; set; }


        public negociosController(MyDbContext context)
        {
            _context = context;
            _firebase = new firebaseNegocio();
        }
        public async Task<IActionResult> Index()
        {
            // Consultar la nube
            var data = _firebase.list();
            foreach (var item in data)
            {
                MyFbContext.modelNegocio model = JsonConvert.DeserializeObject<MyFbContext.modelNegocio>(((JProperty)item).Value.ToString());
                string llave = item.Name.ToString();

                // Modelo real
                var m = new negocio
                {
                    idnegocio = llave,
                    Estatus = model.Estatus,
                    calificacion = model.calificacion,
                    calle = model.calle,
                    ciudad = model.ciudad,
                    colonia = model.colonia,
                    cp = model.cp,
                    descripcion = model.descripcion,
                    domingoFin = model.domingoFin,
                    domingoInicio = model.domingoInicio,
                    domingock = model.domingock,
                    email = model.email,
                    especialidad = model.especialidad,
                    estado = model.estado,
                    estrellas = model.estrellas,
                    juevesFin = model.juevesFin,
                    juevesInicio = model.juevesInicio,
                    latitud = model.latitud,
                    longitud = model.longitud,
                    lunesFin = model.lunesFin,
                    lunesInicio = model.lunesInicio,
                    lunesck = model.lunesck,
                    martesFin = model.martesFin,
                    martesInicio = model.martesInicio,
                    martesck = model.martesck,
                    miercolesFin = model.miercolesFin,
                    miercolesInicio = model.miercolesInicio,
                    miercolesck = model.miercolesck,
                    municipio = model.municipio,
                    nombreComercial = model.nombreComercial,
                    numext = model.numext,
                    numint = model.numint,
                    profileImage = model.profileImage,
                    razonSocial = model.razonSocial,
                    rfc = model.rfc,
                    sabadoFin = model.sabadoFin,
                    sabadoInicio = model.sabadoInicio,
                    sabadock = model.sabadock,
                    telefono = model.telefono,
                    tipo = model.tipo,
                    viajes = model.viajes,
                    viernesFin = model.viernesFin,
                    viernesInicio = model.viernesInicio,
                    viernesck = model.viernesck
                };

                if (negocioExists(m.idnegocio).Equals(true))
                {
                    var neg = await _context.Negocios.FirstOrDefaultAsync(o => o.idnegocio == m.idnegocio);
                    neg.idnegocio = llave;
                    neg.Estatus = model.Estatus;
                    neg.calificacion = model.calificacion;
                    neg.calle = model.calle;
                    neg.ciudad = model.ciudad;
                    neg.colonia = model.colonia;
                    neg.cp = model.cp;
                    neg.descripcion = model.descripcion;
                    neg.domingoFin = model.domingoFin;
                    neg.domingoInicio = model.domingoInicio;
                    neg.domingock = model.domingock;
                    neg.email = model.email;
                    neg.especialidad = model.especialidad;
                    neg.estado = model.estado;
                    neg.estrellas = model.estrellas;
                    neg.juevesFin = model.juevesFin;
                    neg.juevesInicio = model.juevesInicio;
                    neg.latitud = model.latitud;
                    neg.longitud = model.longitud;
                    neg.lunesFin = model.lunesFin;
                    neg.lunesInicio = model.lunesInicio;
                    neg.lunesck = model.lunesck;
                    neg.martesFin = model.martesFin;
                    neg.martesInicio = model.martesInicio;
                    neg.martesck = model.martesck;
                    neg.miercolesFin = model.miercolesFin;
                    neg.miercolesInicio = model.miercolesInicio;
                    neg.miercolesck = model.miercolesck;
                    neg.municipio = model.municipio;
                    neg.nombreComercial = model.nombreComercial;
                    neg.numext = model.numext;
                    neg.numint = model.numint;
                    neg.profileImage = model.profileImage;
                    neg.razonSocial = model.razonSocial;
                    neg.rfc = model.rfc;
                    neg.sabadoFin = model.sabadoFin;
                    neg.sabadoInicio = model.sabadoInicio;
                    neg.sabadock = model.sabadock;
                    neg.telefono = model.telefono;
                    neg.tipo = model.tipo;
                    neg.viajes = model.viajes;
                    neg.viernesFin = model.viernesFin;
                    neg.viernesInicio = model.viernesInicio;
                    neg.viernesck = model.viernesck;
                    _context.Update(neg);
                    await _context.SaveChangesAsync();
                }
                else
                {

                    _context.Add(m);
                    await _context.SaveChangesAsync();
                }

            }

            return View(await _context.Negocios.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string searchString, string campo)
        {
            var negocios = from m in _context.Negocios
                         select m;


            switch(campo)
            {
                case "Nombre":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        negocios = negocios.Where(s => s.nombreComercial!.Contains(searchString));
                    }
                    break;
                case "Telefono":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        negocios = negocios.Where(s => s.telefono!.Contains(searchString));
                    }
                    break;
                case "Estatus":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        negocios = negocios.Where(s => s.Estatus.Equals(searchString));
                    }
                    break;
            }

            return View(await negocios.ToListAsync());
        }
        public async Task<IActionResult> Edit(int id)
        {
            negocio model;

            if (negocioExists(id).Equals(false))
            {
                return NotFound();
            }
            else
            {
                model = await _context.Negocios.FindAsync(id);

                // Consultar firebase (mostrara la info mas actual)
                model = _firebase.details(model.idnegocio, model.id);
                if (model == null)
                {
                    return NotFound();
                }

                return PartialView(model);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string idnegocio, [Bind("id,idnegocio,Estatus,calificacion,calle,ciudad,colonia,cp,descripcion,domingoFin,domingoInicio,domingock,email,especialidad,estado,estrellas,juevesFin,juevesInicio,latitud,longitud,lunesFin,lunesInicio,lunesck,martesFin,martesInicio,martesck,miercolesFin,miercolesInicio,miercolesck,municipio,nombreComercial,numext,numint,profileImage,razonSocial,rfc,sabadoFin,sabadoInicio,sabadock,telefono,tipo,viajes,viernesFin,viernesInicio,viernesck")] negocio negocio)
        {
            if (id != negocio.id)
            {
                return NotFound();
            }
            if (idnegocio is null)
            {
                return NotFound();
            }

            // Consultar firebase
            var model = _firebase.details(idnegocio, id);
            model.Estatus = negocio.Estatus;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(negocio);
                    await _context.SaveChangesAsync();

                    // Actualizar en Firebase
                    _firebase.update(model.idnegocio, model.Estatus);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!negocioExists(negocio.idnegocio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return PartialView(negocio);
        }
        private bool negocioExists(string idnegocio)
        {

Views/negocios/Create.cshtml
@model kairh_admin.Models.negocio

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>negocio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idnegocio" class="control-label"></label>
                <input asp-for="idnegocio" class="form-control" />
                <span asp-validation-for="idnegocio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estatus" class="control-label"></label>
                <input asp-for="Estatus" class="form-control" />
                <span asp-validation-for="Estatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="calificacion" class="control-label"></label>
                <input asp-for="calificacion" class="form-control" />
                <span asp-validation-for="calificacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="calle" class="control-label"></label>
                <input asp-for="calle" class="form-control" />
                <span asp-validation-for="calle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ciudad" class="control-label"></label>
                <input asp-for="ciudad" class="form-control" />
                <span asp-validation-for="ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="colonia" class="control-label"></label>
                <input asp-for="colonia" class="form-control" />
                <span asp-validation-for="colonia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cp" class="control-label"></label>
                <input asp-for="cp" class="form-control" />
                <span asp-validation-for="cp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="domingoFin" class="control-label"></label>
                <input asp-for="domingoFin" class="form-control" />
                <span asp-validation-for="domingoFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="domingoInicio" class="control-label"></label>
                <input asp-for="domingoInicio" class="form-control" />
                <span asp-validation-for="domingoInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="domingock" class="control-label"></label>
                <input asp-for="domingock" class="form-control" />
                <span asp-validation-for="domingock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="especialidad" class="control-label"></label>
                <input asp-for="especialidad" class="form-control" />
                <span asp-validation-for="especialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estado" class="control-label"></label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estrellas" class="control-label"></label>
                <input asp-for="estrellas" class="form-control" />
                <span asp-validation-for="estrellas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="juevesFin" class="control-label"></label>
                <input asp-for="juevesFin" class="form-control" />
                <span asp-validation-for="juevesFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="juevesInicio" class="control-label"></label>
                <input asp-for="juevesInicio" class="form-control" />
                <span asp-validation-for="juevesInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="latitud" class="control-label"></label>
                <input asp-for="latitud" class="form-control" />
                <span asp-validation-for="latitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="longitud" class="control-label"></label>
                <input asp-for="longitud" class="form-control" />
                <span asp-validation-for="longitud" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lunesFin" class="control-label"></label>
                <input asp-for="lunesFin" class="form-control" />
                <span asp-validation-for="lunesFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lunesInicio" class="control-label"></label>
                <input asp-for="lunesInicio" class="form-control" />
                <span asp-validation-for="lunesInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lunesck" class="control-label"></label>
                <input asp-for="lunesck" class="form-control" />
                <span asp-validation-for="lunesck" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="martesFin" class="control-label"></label>
                <input asp-for="martesFin" class="form-control" />
                <span asp-validation-for="martesFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="martesInicio" class="control-label"></label>
                <input asp-for="martesInicio" class="form-control" />
                <span asp-validation-for="martesInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="martesck" class="control-label"></label>
                <input asp-for="martesck" class="form-control" />
                <span asp-validation-for="martesck" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="miercolesFin" class="control-label"></label>
                <input asp-for="miercolesFin" class="form-control" />
                <span asp-validation-for="miercolesFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="miercolesInicio" class="control-label"></label>
                <input asp-for="miercolesInicio" class="form-control" />
                <span asp-validation-for="miercolesInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="miercolesck" class="control-label"></label>
                <input asp-for="miercolesck" class="form-control" />
                <span asp-validation-for="miercolesck" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="municipio" class="control-label"></label>
                <input asp-for="municipio" class="form-control" />
                <span asp-validation-for="municipio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombreComercial" class="control-label"></label>
                <input asp-for="nombreComercial" class="form-control" />
                <span asp-validation-for="nombreComercial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numext" class="control-label"></label>
                <input asp-for="numext" class="form-control" />
                <span asp-validation-for="numext" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numint" class="control-label"></label>
                <input asp-for="numint" class="form-control" />
                <span asp-validation-for="numint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="profileImage" class="control-label"></label>
                <input asp-for="profileImage" class="form-control" />
                <span asp-validation-for="profileImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="razonSocial" class="control-label"></label>
                <input asp-for="razonSocial" class="form-control" />
                <span asp-validation-for="razonSocial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rfc" class="control-label"></label>
                <input asp-for="rfc" class="form-control" />
                <span asp-validation-for="rfc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sabadoFin" class="control-label"></label>
                <input asp-for="sabadoFin" class="form-control" />
                <span asp-validation-for="sabadoFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sabadoInicio" class="control-label"></label>
                <input asp-for="sabadoInicio" class="form-control" />
                <span asp-validation-for="sabadoInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="sabadock" class="control-label"></label>
                <input asp-for="sabadock" class="form-control" />
                <span asp-validation-for="sabadock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tipo" class="control-label"></label>
                <input asp-for="tipo" class="form-control" />
                <span asp-validation-for="tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="viajes" class="control-label"></label>
                <input asp-for="viajes" class="form-control" />
                <span asp-validation-for="viajes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="viernesFin" class="control-label"></label>
                <input asp-for="viernesFin" class="form-control" />
                <span asp-validation-for="viernesFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="viernesInicio" class="control-label"></label>
                <input asp-for="viernesInicio" class="form-control" />
                <span asp-validation-for="viernesInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="viernesck" class="control-label"></label>
                <input asp-for="viernesck" class="form-control" />
                <span asp-validation-for="viernesck" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/negocios/Edit.cshtml
@model kairh_admin.Models.negocio

@{
    ViewBag.Title = "Negocio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="modal-header">
            <table cellpadding="5">
                <tr>
                    <td >
                        <img src=@Model.profileImage class="img-fluid img-thumbnail" width="80" alt="">
                    </td>
                    <td>
                        <h5 class="modal-title" style="color: #00ADEF">@Model.nombreComercial.ToString()</h5>
                        <p style="color: gray">@Model.descripcion.ToString()</p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="modal-body">

            @Html.HiddenFor(model => model.idnegocio, new { Value = Model.idnegocio })

            <strong>
                Estatus:
                <select class="form-control" name="estatus">
                    @if (Model.Estatus.ToLower().Equals("activo"))
                    {
                        <option value="Activo" selected>Activo</option>
                        <option value="Inactivo">Inactivo</option>
                        <option value="Revisar">Revisar</option>
                    }
                    else
                    {
                        <option value="Activo">Activo</option>
                        if (Model.Estatus.ToLower().Equals("inactivo"))
                        {
                            <option value="Inactivo" selected>Inactivo</option>
                            <option value="Revisar">Revisar</option>
                        }
                        else
                        {
                            <option value="Inactivo">Inactivo</option>
                            if (Model.Estatus.ToLower().Equals("revisar"))
                            {
                                <option value="Revisar" selected>Revisar</option>
                            }
                            else
                            {
                                <option value="Revisar">Revisar</option>
                            }
                        }
                    }
                </select>
            </strong>
                <!--<table>
    <tr>
        <td>
        </td>
        <td>
            <strong>-->
                @*@Html.LabelFor(model => model.estatus, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @*<p>*@
                @*</p>*@
                <!--</strong>
            </td>
        </tr>
    </table>-->
</div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <input id="resultado" type="submit" value="Guardar" class="btn btn-success" />
        </div>

    </div>
}

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

Views/negocios/Index.cshtml
@model IEnumerable<kairh_admin.Models.negocio>

@{
    ViewData["Title"] = "Negocios";
}

<br />
<div class="container">
    <div class="form-inline">
        <div class="form-group">
            @*<img src="~/img/negocio.png" width="55" class="img-fluid" style="margin-right:20px" />*@
            <h2 class="display-4">Catálogo de Negocios</h2>
        </div>
    </div>
</div>

<br />
@*buscador*@
<form class="form-inline" asp-controller="negocios" asp-action="Index" style="margin-left:25px">
    <label class="col-form-label" for="exampleFormControlSelect1">Buscar por: </label>
    <div class="col-auto">

        <select class="form-control"  name="campo">
            <option>Nombre</option>
            <option>Telefono</option>
            <option>Estatus</option>
        </select>
        <input name="SearchString" class="form-control mr-sm-2" type="search" aria-label="Search">

        <div class="btn-group" role="group" aria-label="Basic example">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><img src="~/img/buscar.png" align="middle" width="19" height="19" /></button>
            <a class="btn btn-outline-secondary my-2 my-sm-0" asp-area="" asp-controller="negocios" asp-action="Index"><img src="~/img/refresh.png" style="align-content:center" width="19" height="19" /></a>
        </div>

        </div>
</form>

<br />
<br />
<table class="table table-striped">
    <thead class="thead-light">
        <tr>
            <th style="text-align:center">
                LOGO
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreComercial)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.Estatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th style="text-align:center">
                @Html.DisplayName("ACCIONES")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr >
                <td style="text-align:center">
                    <img src=@item.profileImage class="img-fluid img-thumbnail" width="70" alt="">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombreComercial)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Estatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td style="text-align:center">
                    @Html.ActionLink("Editar", "Edit", new { id = item.id }, new { @class = "btn btn-secondary", data_modal = "" })
                </td>
            </tr>
        }
    </tbody>
</table>