Controllers/repartidoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kairh_admin.Models;
using kairh_admin.Models.firebase;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using FireSharp;

namespace kairh_admin.Controllers
{
    public class repartidoresController : Controller
    {
        private readonly MyDbContext _context;
        public firebaseRepartidor _firebase { get; set; }


        public repartidoresController(MyDbContext context)
        {
            _context = context;
            _firebase = new firebaseRepartidor();
        }
        public async Task<IActionResult> Index()
        {
            // Consultar la nube
            var data = _firebase.list();
            foreach (var item in data)
            {
                MyFbContext.modelRepartidor model = JsonConvert.DeserializeObject<MyFbContext.modelRepartidor>(((JProperty)item).Value.ToString());
                string llave = item.Name.ToString();
                var m = new repartidor
                {
                    idrepartidor = llave,
                    clave = model.clave,
                    correo = model.correo,
                    estatus = model.estatus,
                    nombre = model.nombre,
                    telefono = model.telefono,
                };

                if(repartidorExists(m.idrepartidor).Equals(true))
                {
                    var rep = await _context.Repartidores.FirstOrDefaultAsync(o => o.idrepartidor == m.idrepartidor);
                    rep.idrepartidor = llave;
                    rep.clave = model.clave;
                    rep.correo = model.correo;
                    rep.estatus = model.estatus;
                    rep.nombre = model.nombre;
                    rep.telefono = model.telefono;

                    _context.Update(rep);
                    await _context.SaveChangesAsync();
                }
                else
                {

                    _context.Add(m);
                    await _context.SaveChangesAsync();
                }

            }

            return View(await _context.Repartidores.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string searchString, string campo)
        {
            var repartidores = from m in _context.Repartidores
                           select m;


            switch (campo)
            {
                case "Nombre":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        repartidores = repartidores.Where(s => s.nombre!.Contains(searchString));
                    }
                    break;
                case "Telefono":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        repartidores = repartidores.Where(s => s.telefono!.Contains(searchString));
                    }
                    break;
                case "Estatus":
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        repartidores = repartidores.Where(s => s.estatus.Equals(searchString));
                    }
                    break;
            }

            return View(await repartidores.ToListAsync());
        }
        public async Task<IActionResult> Edit(int id)
        {
            repartidor model;

            if (repartidorExists(id).Equals(false))
            {
                return NotFound();
            }
            else
            {
                model = await _context.Repartidores.FindAsync(id);

                // Consultar firebase (mostrara la info mas actual)
                model = _firebase.details(model.idrepartidor, model.id);
                if (model == null)
                {
                    return NotFound();
                }

                return PartialView(model);
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string idrepartidor, [Bind("id,idrepartidor,clave,correo,estatus,nombre,telefono")] repartidor repartidor)
        {
            if (id != repartidor.id)
            {
                return NotFound();
            }
            if (idrepartidor is null)
            {
                return NotFound();
            }

            // Consultar firebase
            var model = _firebase.details(idrepartidor, id);
            model.estatus = repartidor.estatus;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(repartidor);
                    await _context.SaveChangesAsync();

                    // Actualizar en Firebase
                    _firebase.update(model.idrepartidor, model.estatus);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!repartidorExists(repartidor.idrepartidor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return PartialView(repartidor);
        }
        private bool repartidorExists(string idrepartidor)
        {
            return _context.Repartidores.Any(e => e.idrepartidor == idrepartidor);
        }
        private bool repartidorExists(int id)
        {
            return _context.Repartidores.Any(e => e.id == id);
        }

        //private bool repartidorExists(int id)
        //{
        //    return _context.Repartidores.Any(e => e.id == id);
        //}



        ////public async Task<IActionResult> CreateInt([Bind("id,idrepartidor,clave,correo,estatus,nombre,telefono")] repartidor repartidor)
        ////{
        ////    if (ModelState.IsValid)
        ////    {
        ////        _context.Add(repartidor);
        ////        await _context.SaveChangesAsync();
        ////        //return RedirectToAction(nameof(Index));
        ////    }
        ////    //return View(repartidor);
        ////    return RedirectToAction(nameof(Index));
        ////}
        //private async Task<IActionResult> EditInt(repartidor repartidor)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            // Consultar firebase
        //            //var model = _firebase.details(repartidor.idrepartidor, repartidor.id);

        //            _context.Update(repartidor);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!repartidorExists(repartidor.id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return RedirectToAction(nameof(Index));
        //}
        //// GET: repartidores
        ////public async Task<IActionResult> Index()
        //public async Task<IActionResult> Index()
        //{
        //    // Consultar de firebase
        //    ////_firebase._client = new FireSharp.FirebaseClient(config);
        //    //FirebaseResponse response = _firebase.client.Get("Repartidores");
        //    //dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
        //    var list = _firebase.list();
        //    //sincronizar(list);


        //    foreach (var item in list)
        //    {
        //        repartidor nuevo = new repartidor();
        //        nuevo = item;
        //        //bool existencia = repartidorExists(item.idrepartidor.ToString());
        //        item.id = _context.Repartidores.FirstOrDefault(m => m.idrepartidor == item.idrepartidor).id;

        //        if (item.id<=0)
        //        {
        //            _context.Add(item);
        //            await _context.SaveChangesAsync();
        //        }
        //        else
        //        {
        //            //item.id = clave(item.idrepartidor);
        //            //var nuevo = item;
        //            //nuevo.id = _context.Repartidores.FirstOrDefault(m => m.idrepartidor == item.idrepartidor).id;
        //            nuevo.id = item.id;

        //            _context.Update(nuevo);
        //            await _context.SaveChangesAsync();
        //        }
        //    }

        //    //foreach (var item in data)
        //    //{
        //    //    _firebase.fbRepartidor oRep = JsonConvert.DeserializeObject<_firebase.fbRepartidor>(((JProperty)item).Value.ToString());
        //    //    bool existencia = repartidorExists(item.Name.ToString());
        //    //    if (existencia.Equals(false))
        //    //    {
        //    //        // Crear Modelo Válido y ejecutar create
        //    //        repartidor repartidorNuevo = new repartidor()
        //    //        {
        //    //            idrepartidor = item.Name.ToString(),
        //    //            clave = oRep.clave,
        //    //            correo = oRep.correo,
        //    //            estatus = oRep.estatus,
        //    //            nombre = oRep.nombre,
        //    //            telefono = oRep.telefono,
        //    //        };

Views/repartidores/Create.cshtml
@model kairh_admin.Models.repartidor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>repartidor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idrepartidor" class="control-label"></label>
                <input asp-for="idrepartidor" class="form-control" />
                <span asp-validation-for="idrepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="clave" class="control-label"></label>
                <input asp-for="clave" class="form-control" />
                <span asp-validation-for="clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="correo" class="control-label"></label>
                <input asp-for="correo" class="form-control" />
                <span asp-validation-for="correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estatus" class="control-label"></label>
                <input asp-for="estatus" class="form-control" />
                <span asp-validation-for="estatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefono" class="control-label"></label>
                <input asp-for="telefono" class="form-control" />
                <span asp-validation-for="telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/repartidores/Delete.cshtml
@model kairh_admin.Models.repartidor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>repartidor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idrepartidor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idrepartidor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.clave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.clave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/repartidores/Details.cshtml
@model kairh_admin.Models.repartidor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>repartidor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idrepartidor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idrepartidor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.clave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.clave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefono)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/repartidores/Edit.cshtml
@model kairh_admin.Models.repartidor

@{
    ViewBag.Title = "Repartidor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
@{
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="modal-header">
        <table cellpadding="5">
            <tr>
                <td>
                    <img src="~/img/repartidor.png" class="img-fluid img-thumbnail" width="80" alt="">
                </td>
                <td>
                    <h5 class="modal-title" style="color: #00ADEF">@Model.nombre.ToString()</h5>
                    <p style="color: gray">@Model.correo.ToString()</p>
                </td>
            </tr>
        </table>
    </div>

    <div class="modal-body">
        @Html.HiddenFor(model => model.idrepartidor, new { Value = Model.idrepartidor })

        <strong>
            Estatus:
            <select class="form-control" name="estatus">
                @if (Model.estatus.ToLower().Equals("activo"))
                {
                    <option value="Activo" selected>Activo</option>
                    <option value="Inactivo">Inactivo</option>
                    <option value="Revisar">Revisar</option>
                }
                else
                {
                    <option value="Activo">Activo</option>
                    if (Model.estatus.ToLower().Equals("inactivo"))
                    {
                        <option value="Inactivo" selected>Inactivo</option>
                        <option value="Revisar">Revisar</option>
                    }
                    else
                    {
                        <option value="Inactivo">Inactivo</option>
                        if (Model.estatus.ToLower().Equals("revisar"))
                        {
                            <option value="Revisar" selected>Revisar</option>
                        }
                        else
                        {
                            <option value="Revisar">Revisar</option>
                        }
                    }
                }
            </select>
        </strong>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <input id="resultado" type="submit" value="Guardar" class="btn btn-success" />
    </div>

</div>
}


@*
        **** A N T E R I O R ****
        <h1>Edit</h1>

    <h4>repartidor</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="id" />
                <div class="form-group">
                    <label asp-for="idrepartidor" class="control-label"></label>
                    <input asp-for="idrepartidor" class="form-control" />
                    <span asp-validation-for="idrepartidor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="clave" class="control-label"></label>
                    <input asp-for="clave" class="form-control" />
                    <span asp-validation-for="clave" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="correo" class="control-label"></label>
                    <input asp-for="correo" class="form-control" />
                    <span asp-validation-for="correo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="estatus" class="control-label"></label>
                    <input asp-for="estatus" class="form-control" />
                    <span asp-validation-for="estatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="nombre" class="control-label"></label>
                    <input asp-for="nombre" class="form-control" />
                    <span asp-validation-for="nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="telefono" class="control-label"></label>
                    <input asp-for="telefono" class="form-control" />
                    <span asp-validation-for="telefono" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

Views/repartidores/Index.cshtml
@model IEnumerable<kairh_admin.Models.repartidor>

@{
    ViewData["Title"] = "Repartidores";
}


<br />
<div class="container">
    <div class="form-inline">
        <div class="form-group">
            @*<img src="~/img/repartidor_cat.png" width="55" class="img-fluid" style="margin-right:20px" />*@
            <h6 class="display-4">Catálogo de Repartidores</h6>
        </div>
    </div>
</div>

<br />
@*buscador*@
<form class="form-inline" asp-controller="repartidores" asp-action="Index" style="margin-left:25px">
    <label class="col-form-label" for="exampleFormControlSelect1">Buscar por: </label>
    <div class="col-auto">

        <select class="form-control" name="campo">
            <option>Nombre</option>
            <option>Telefono</option>
            <option>Estatus</option>
        </select>
        <input name="SearchString" class="form-control mr-sm-2" type="search" aria-label="Search">

        <div class="btn-group" role="group" aria-label="Basic example">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><img src="~/img/buscar.png" align="middle" width="19" height="19" /></button>
            <a class="btn btn-outline-secondary my-2 my-sm-0" asp-area="" asp-controller="repartidores" asp-action="Index"><img src="~/img/refresh.png" style="align-content:center" width="19" height="19" /></a>
        </div>

    </div>
</form>

<br />
<br />
<table class="table table-striped">
    <thead class="table thead-light">
        <tr>
            <th style="text-align:center">
                FOTO
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.estatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.correo)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th style="text-align:center">
                @Html.DisplayName("ACCIONES")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    <img src="~/img/repartidor.png"class="img-fluid img-thumbnail" width="45" alt="">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.estatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.correo)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td style="text-align:center">
                    @Html.ActionLink("Editar", "Edit", new { id = item.id }, new { @class = "btn btn-secondary", data_modal = "" })
                </td>
            </tr>
        }
    </tbody>
</table>